package com.example.wishlist.services;

import com.example.wishlist.models.WishModel;
import com.example.wishlist.repositories.WishRepository;
import com.example.wishlist.repositories.WishlistRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class WishService {

    private final WishRepository wishRepos;
    private final WishlistRepository wishlistRepos;

    // Constructor injection
    // Spring calls this constructor to provide an autogenerated
    // implementation of the WishRepository interface
    public WishService(WishRepository wishRepos, WishlistRepository wishlistRepos) {
        this.wishRepos = wishRepos;
        this.wishlistRepos = wishlistRepos;
    }

    public List<WishModel> getWishes() {
        return wishRepos.findAll();
    }

    public WishModel getWish(long id) {
        return wishRepos.findById(id);
    }

    public long addWish(String name, String url, long wishlistId) {
        WishModel wish = new WishModel(name,url);
        wishRepos.insertWish(wish);
        wishlistRepos.mapWish(wishlistId,wish.getId());
        return wish.getId();
    }
    // Update wl, except list of wishes
    public void updateWish(WishModel wish) {
        wishRepos.update(wish);
    }
}
