package com.example.wishlist.services;

import com.example.wishlist.models.UserModel;
import com.example.wishlist.models.WishModel;
import com.example.wishlist.models.WishlistModel;
import com.example.wishlist.repositories.UserRepository;
import com.example.wishlist.repositories.WishlistRepository;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.security.Principal;
import java.util.List;

@Service
public class WishlistService {

    private final WishlistRepository wishlistRepos;
    private final UserRepository userRepos;

    // Constructor injection
    // Spring calls this constructor to provide an autogenerated
    // implementation of the WishlistRepository interface
    public WishlistService(WishlistRepository wishlistRepos, UserRepository userRepository) {
        this.wishlistRepos = wishlistRepos;
        this.userRepos = userRepository;
    }

    public List<WishlistModel> getWishlists() {
        return user().getWishlists();
    }

    private UserModel user() {
        Principal principal = SecurityContextHolder.getContext().getAuthentication();
        return userRepos.findUserByUsername(principal.getName());
    }

    public WishlistModel getWishlist(long id) {
        return wishlistRepos.findById(id);
    }

    public long addWishlist(String name) {
        WishlistModel wl = new WishlistModel(name);
        wishlistRepos.insertWishlist(wl);
        userRepos.mapWishlist(user().getId(), wl.getId());
        return wl.getId();
    }
    // Update wl, except list of wishes
    public void updateWishlist(WishlistModel wl) {
        wishlistRepos.update(wl);
    }

    public void addWishToWishlist(WishlistModel wl, WishModel wish) {
        wl.getWishes().add(wish);
        // update wishlist_wish mapping table in database
        wishlistRepos.mapWish(wl.getId(), wish.getId());
    }
}
